//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistantUpdater.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.catarc.info/", ConfigurationName="Services.FlexService")]
    public interface FlexService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.userRegisterResponse userRegister(AssistantUpdater.Services.userRegister request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.ufileUploadResponse ufileUpload(AssistantUpdater.Services.ufileUpload request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.getBbhResponse getBbh(AssistantUpdater.Services.getBbh request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.ufileDownloadResponse ufileDownload(AssistantUpdater.Services.ufileDownload request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.getAllEnterpriseResponse getAllEnterprise(AssistantUpdater.Services.getAllEnterprise request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.fillRuleDowloadResponse fillRuleDowload(AssistantUpdater.Services.fillRuleDowload request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.fillRuleUploadResponse fillRuleUpload(AssistantUpdater.Services.fillRuleUpload request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.fillRuleMdStrResponse fillRuleMdStr(AssistantUpdater.Services.fillRuleMdStr request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.ufileDetailGetResponse ufileDetailGet(AssistantUpdater.Services.ufileDetailGet request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.userDeleteResponse userDelete(AssistantUpdater.Services.userDelete request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.ufileDeleteResponse ufileDelete(AssistantUpdater.Services.ufileDelete request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        AssistantUpdater.Services.userLoginResponse userLogin(AssistantUpdater.Services.userLogin request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userRegister {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userRegister", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.userRegisterBody Body;
        
        public userRegister() {
        }
        
        public userRegister(AssistantUpdater.Services.userRegisterBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class userRegisterBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        public userRegisterBody() {
        }
        
        public userRegisterBody(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userRegisterResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.userRegisterResponseBody Body;
        
        public userRegisterResponse() {
        }
        
        public userRegisterResponse(AssistantUpdater.Services.userRegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class userRegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public userRegisterResponseBody() {
        }
        
        public userRegisterResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ufileUpload {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ufileUpload", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.ufileUploadBody Body;
        
        public ufileUpload() {
        }
        
        public ufileUpload(AssistantUpdater.Services.ufileUploadBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ufileUploadBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] arg3;
        
        public ufileUploadBody() {
        }
        
        public ufileUploadBody(string arg0, string arg1, string arg2, byte[] arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ufileUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ufileUploadResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.ufileUploadResponseBody Body;
        
        public ufileUploadResponse() {
        }
        
        public ufileUploadResponse(AssistantUpdater.Services.ufileUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ufileUploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ufileUploadResponseBody() {
        }
        
        public ufileUploadResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBbh {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBbh", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.getBbhBody Body;
        
        public getBbh() {
        }
        
        public getBbh(AssistantUpdater.Services.getBbhBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBbhBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getBbhBody() {
        }
        
        public getBbhBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBbhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBbhResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.getBbhResponseBody Body;
        
        public getBbhResponse() {
        }
        
        public getBbhResponse(AssistantUpdater.Services.getBbhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBbhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getBbhResponseBody() {
        }
        
        public getBbhResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ufileDownload {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ufileDownload", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.ufileDownloadBody Body;
        
        public ufileDownload() {
        }
        
        public ufileDownload(AssistantUpdater.Services.ufileDownloadBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ufileDownloadBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public ufileDownloadBody() {
        }
        
        public ufileDownloadBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ufileDownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ufileDownloadResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.ufileDownloadResponseBody Body;
        
        public ufileDownloadResponse() {
        }
        
        public ufileDownloadResponse(AssistantUpdater.Services.ufileDownloadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ufileDownloadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] @return;
        
        public ufileDownloadResponseBody() {
        }
        
        public ufileDownloadResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllEnterprise {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllEnterprise", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.getAllEnterpriseBody Body;
        
        public getAllEnterprise() {
        }
        
        public getAllEnterprise(AssistantUpdater.Services.getAllEnterpriseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllEnterpriseBody {
        
        public getAllEnterpriseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllEnterpriseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllEnterpriseResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.getAllEnterpriseResponseBody Body;
        
        public getAllEnterpriseResponse() {
        }
        
        public getAllEnterpriseResponse(AssistantUpdater.Services.getAllEnterpriseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getAllEnterpriseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getAllEnterpriseResponseBody() {
        }
        
        public getAllEnterpriseResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fillRuleDowload {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fillRuleDowload", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.fillRuleDowloadBody Body;
        
        public fillRuleDowload() {
        }
        
        public fillRuleDowload(AssistantUpdater.Services.fillRuleDowloadBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fillRuleDowloadBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        public fillRuleDowloadBody() {
        }
        
        public fillRuleDowloadBody(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fillRuleDowloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fillRuleDowloadResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.fillRuleDowloadResponseBody Body;
        
        public fillRuleDowloadResponse() {
        }
        
        public fillRuleDowloadResponse(AssistantUpdater.Services.fillRuleDowloadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fillRuleDowloadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] @return;
        
        public fillRuleDowloadResponseBody() {
        }
        
        public fillRuleDowloadResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fillRuleUpload {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fillRuleUpload", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.fillRuleUploadBody Body;
        
        public fillRuleUpload() {
        }
        
        public fillRuleUpload(AssistantUpdater.Services.fillRuleUploadBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fillRuleUploadBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] arg5;
        
        public fillRuleUploadBody() {
        }
        
        public fillRuleUploadBody(string arg0, string arg1, string arg2, string arg3, string arg4, byte[] arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fillRuleUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fillRuleUploadResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.fillRuleUploadResponseBody Body;
        
        public fillRuleUploadResponse() {
        }
        
        public fillRuleUploadResponse(AssistantUpdater.Services.fillRuleUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fillRuleUploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fillRuleUploadResponseBody() {
        }
        
        public fillRuleUploadResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fillRuleMdStr {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fillRuleMdStr", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.fillRuleMdStrBody Body;
        
        public fillRuleMdStr() {
        }
        
        public fillRuleMdStr(AssistantUpdater.Services.fillRuleMdStrBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fillRuleMdStrBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        public fillRuleMdStrBody() {
        }
        
        public fillRuleMdStrBody(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fillRuleMdStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fillRuleMdStrResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.fillRuleMdStrResponseBody Body;
        
        public fillRuleMdStrResponse() {
        }
        
        public fillRuleMdStrResponse(AssistantUpdater.Services.fillRuleMdStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fillRuleMdStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fillRuleMdStrResponseBody() {
        }
        
        public fillRuleMdStrResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ufileDetailGet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ufileDetailGet", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.ufileDetailGetBody Body;
        
        public ufileDetailGet() {
        }
        
        public ufileDetailGet(AssistantUpdater.Services.ufileDetailGetBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ufileDetailGetBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public ufileDetailGetBody() {
        }
        
        public ufileDetailGetBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ufileDetailGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ufileDetailGetResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.ufileDetailGetResponseBody Body;
        
        public ufileDetailGetResponse() {
        }
        
        public ufileDetailGetResponse(AssistantUpdater.Services.ufileDetailGetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ufileDetailGetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ufileDetailGetResponseBody() {
        }
        
        public ufileDetailGetResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userDelete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userDelete", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.userDeleteBody Body;
        
        public userDelete() {
        }
        
        public userDelete(AssistantUpdater.Services.userDeleteBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class userDeleteBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public userDeleteBody() {
        }
        
        public userDeleteBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userDeleteResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.userDeleteResponseBody Body;
        
        public userDeleteResponse() {
        }
        
        public userDeleteResponse(AssistantUpdater.Services.userDeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class userDeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public userDeleteResponseBody() {
        }
        
        public userDeleteResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ufileDelete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ufileDelete", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.ufileDeleteBody Body;
        
        public ufileDelete() {
        }
        
        public ufileDelete(AssistantUpdater.Services.ufileDeleteBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ufileDeleteBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public ufileDeleteBody() {
        }
        
        public ufileDeleteBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ufileDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ufileDeleteResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.ufileDeleteResponseBody Body;
        
        public ufileDeleteResponse() {
        }
        
        public ufileDeleteResponse(AssistantUpdater.Services.ufileDeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ufileDeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ufileDeleteResponseBody() {
        }
        
        public ufileDeleteResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userLogin {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userLogin", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.userLoginBody Body;
        
        public userLogin() {
        }
        
        public userLogin(AssistantUpdater.Services.userLoginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class userLoginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public userLoginBody() {
        }
        
        public userLoginBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userLoginResponse", Namespace="http://www.catarc.info/", Order=0)]
        public AssistantUpdater.Services.userLoginResponseBody Body;
        
        public userLoginResponse() {
        }
        
        public userLoginResponse(AssistantUpdater.Services.userLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class userLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public userLoginResponseBody() {
        }
        
        public userLoginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlexServiceChannel : AssistantUpdater.Services.FlexService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlexServiceClient : System.ServiceModel.ClientBase<AssistantUpdater.Services.FlexService>, AssistantUpdater.Services.FlexService {
        
        public FlexServiceClient() {
        }
        
        public FlexServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlexServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlexServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlexServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.userRegisterResponse AssistantUpdater.Services.FlexService.userRegister(AssistantUpdater.Services.userRegister request) {
            return base.Channel.userRegister(request);
        }
        
        public string userRegister(string arg0, string arg1, string arg2, string arg3) {
            AssistantUpdater.Services.userRegister inValue = new AssistantUpdater.Services.userRegister();
            inValue.Body = new AssistantUpdater.Services.userRegisterBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            AssistantUpdater.Services.userRegisterResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).userRegister(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.ufileUploadResponse AssistantUpdater.Services.FlexService.ufileUpload(AssistantUpdater.Services.ufileUpload request) {
            return base.Channel.ufileUpload(request);
        }
        
        public string ufileUpload(string arg0, string arg1, string arg2, byte[] arg3) {
            AssistantUpdater.Services.ufileUpload inValue = new AssistantUpdater.Services.ufileUpload();
            inValue.Body = new AssistantUpdater.Services.ufileUploadBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            AssistantUpdater.Services.ufileUploadResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).ufileUpload(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.getBbhResponse AssistantUpdater.Services.FlexService.getBbh(AssistantUpdater.Services.getBbh request) {
            return base.Channel.getBbh(request);
        }
        
        public string getBbh(string arg0) {
            AssistantUpdater.Services.getBbh inValue = new AssistantUpdater.Services.getBbh();
            inValue.Body = new AssistantUpdater.Services.getBbhBody();
            inValue.Body.arg0 = arg0;
            AssistantUpdater.Services.getBbhResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).getBbh(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.ufileDownloadResponse AssistantUpdater.Services.FlexService.ufileDownload(AssistantUpdater.Services.ufileDownload request) {
            return base.Channel.ufileDownload(request);
        }
        
        public byte[] ufileDownload(string arg0, string arg1, string arg2) {
            AssistantUpdater.Services.ufileDownload inValue = new AssistantUpdater.Services.ufileDownload();
            inValue.Body = new AssistantUpdater.Services.ufileDownloadBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            AssistantUpdater.Services.ufileDownloadResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).ufileDownload(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.getAllEnterpriseResponse AssistantUpdater.Services.FlexService.getAllEnterprise(AssistantUpdater.Services.getAllEnterprise request) {
            return base.Channel.getAllEnterprise(request);
        }
        
        public string getAllEnterprise() {
            AssistantUpdater.Services.getAllEnterprise inValue = new AssistantUpdater.Services.getAllEnterprise();
            inValue.Body = new AssistantUpdater.Services.getAllEnterpriseBody();
            AssistantUpdater.Services.getAllEnterpriseResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).getAllEnterprise(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.fillRuleDowloadResponse AssistantUpdater.Services.FlexService.fillRuleDowload(AssistantUpdater.Services.fillRuleDowload request) {
            return base.Channel.fillRuleDowload(request);
        }
        
        public byte[] fillRuleDowload(string arg0, string arg1, string arg2, string arg3, string arg4) {
            AssistantUpdater.Services.fillRuleDowload inValue = new AssistantUpdater.Services.fillRuleDowload();
            inValue.Body = new AssistantUpdater.Services.fillRuleDowloadBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            AssistantUpdater.Services.fillRuleDowloadResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).fillRuleDowload(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.fillRuleUploadResponse AssistantUpdater.Services.FlexService.fillRuleUpload(AssistantUpdater.Services.fillRuleUpload request) {
            return base.Channel.fillRuleUpload(request);
        }
        
        public string fillRuleUpload(string arg0, string arg1, string arg2, string arg3, string arg4, byte[] arg5) {
            AssistantUpdater.Services.fillRuleUpload inValue = new AssistantUpdater.Services.fillRuleUpload();
            inValue.Body = new AssistantUpdater.Services.fillRuleUploadBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            AssistantUpdater.Services.fillRuleUploadResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).fillRuleUpload(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.fillRuleMdStrResponse AssistantUpdater.Services.FlexService.fillRuleMdStr(AssistantUpdater.Services.fillRuleMdStr request) {
            return base.Channel.fillRuleMdStr(request);
        }
        
        public string fillRuleMdStr(string arg0, string arg1, string arg2, string arg3, string arg4) {
            AssistantUpdater.Services.fillRuleMdStr inValue = new AssistantUpdater.Services.fillRuleMdStr();
            inValue.Body = new AssistantUpdater.Services.fillRuleMdStrBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            AssistantUpdater.Services.fillRuleMdStrResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).fillRuleMdStr(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.ufileDetailGetResponse AssistantUpdater.Services.FlexService.ufileDetailGet(AssistantUpdater.Services.ufileDetailGet request) {
            return base.Channel.ufileDetailGet(request);
        }
        
        public string ufileDetailGet(string arg0, string arg1) {
            AssistantUpdater.Services.ufileDetailGet inValue = new AssistantUpdater.Services.ufileDetailGet();
            inValue.Body = new AssistantUpdater.Services.ufileDetailGetBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            AssistantUpdater.Services.ufileDetailGetResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).ufileDetailGet(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.userDeleteResponse AssistantUpdater.Services.FlexService.userDelete(AssistantUpdater.Services.userDelete request) {
            return base.Channel.userDelete(request);
        }
        
        public string userDelete(string arg0) {
            AssistantUpdater.Services.userDelete inValue = new AssistantUpdater.Services.userDelete();
            inValue.Body = new AssistantUpdater.Services.userDeleteBody();
            inValue.Body.arg0 = arg0;
            AssistantUpdater.Services.userDeleteResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).userDelete(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.ufileDeleteResponse AssistantUpdater.Services.FlexService.ufileDelete(AssistantUpdater.Services.ufileDelete request) {
            return base.Channel.ufileDelete(request);
        }
        
        public string ufileDelete(string arg0, string arg1) {
            AssistantUpdater.Services.ufileDelete inValue = new AssistantUpdater.Services.ufileDelete();
            inValue.Body = new AssistantUpdater.Services.ufileDeleteBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            AssistantUpdater.Services.ufileDeleteResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).ufileDelete(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AssistantUpdater.Services.userLoginResponse AssistantUpdater.Services.FlexService.userLogin(AssistantUpdater.Services.userLogin request) {
            return base.Channel.userLogin(request);
        }
        
        public string userLogin(string arg0, string arg1, string arg2) {
            AssistantUpdater.Services.userLogin inValue = new AssistantUpdater.Services.userLogin();
            inValue.Body = new AssistantUpdater.Services.userLoginBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            AssistantUpdater.Services.userLoginResponse retVal = ((AssistantUpdater.Services.FlexService)(this)).userLogin(inValue);
            return retVal.Body.@return;
        }
    }
}
