//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="INewEnergyClearingServiceServiceSoapBinding", Namespace="http://service.mai.catarc.info/")]
    public partial class INewEnergyClearingServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback checkEnterpriseOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewEnergyVehicleInfoCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNerdsQynameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewEnergyVehicleInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback helloNewEnergyClearingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public INewEnergyClearingServiceService() {
            this.Url = global::Catarc.Adc.NewEnergyAccountSys.Properties.Settings.Default.Catarc_Adc_NewEnergyAccountSys_NewEnergyWeb_IManufacturersAiService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event checkEnterpriseCompletedEventHandler checkEnterpriseCompleted;
        
        /// <remarks/>
        public event getNewEnergyVehicleInfoCountCompletedEventHandler getNewEnergyVehicleInfoCountCompleted;
        
        /// <remarks/>
        public event getNerdsQynameCompletedEventHandler getNerdsQynameCompleted;
        
        /// <remarks/>
        public event getNewEnergyVehicleInfoCompletedEventHandler getNewEnergyVehicleInfoCompleted;
        
        /// <remarks/>
        public event helloNewEnergyClearingCompletedEventHandler helloNewEnergyClearingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.mai.catarc.info/", ResponseNamespace="http://service.mai.catarc.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string checkEnterprise([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string qymc) {
            object[] results = this.Invoke("checkEnterprise", new object[] {
                        username,
                        password,
                        qymc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkEnterpriseAsync(string username, string password, string qymc) {
            this.checkEnterpriseAsync(username, password, qymc, null);
        }
        
        /// <remarks/>
        public void checkEnterpriseAsync(string username, string password, string qymc, object userState) {
            if ((this.checkEnterpriseOperationCompleted == null)) {
                this.checkEnterpriseOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckEnterpriseOperationCompleted);
            }
            this.InvokeAsync("checkEnterprise", new object[] {
                        username,
                        password,
                        qymc}, this.checkEnterpriseOperationCompleted, userState);
        }
        
        private void OncheckEnterpriseOperationCompleted(object arg) {
            if ((this.checkEnterpriseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkEnterpriseCompleted(this, new checkEnterpriseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.mai.catarc.info/", ResponseNamespace="http://service.mai.catarc.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getNewEnergyVehicleInfoCount([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cpxh, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string year) {
            object[] results = this.Invoke("getNewEnergyVehicleInfoCount", new object[] {
                        username,
                        password,
                        cpxh,
                        year});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getNewEnergyVehicleInfoCountAsync(string username, string password, string cpxh, string year) {
            this.getNewEnergyVehicleInfoCountAsync(username, password, cpxh, year, null);
        }
        
        /// <remarks/>
        public void getNewEnergyVehicleInfoCountAsync(string username, string password, string cpxh, string year, object userState) {
            if ((this.getNewEnergyVehicleInfoCountOperationCompleted == null)) {
                this.getNewEnergyVehicleInfoCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewEnergyVehicleInfoCountOperationCompleted);
            }
            this.InvokeAsync("getNewEnergyVehicleInfoCount", new object[] {
                        username,
                        password,
                        cpxh,
                        year}, this.getNewEnergyVehicleInfoCountOperationCompleted, userState);
        }
        
        private void OngetNewEnergyVehicleInfoCountOperationCompleted(object arg) {
            if ((this.getNewEnergyVehicleInfoCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewEnergyVehicleInfoCountCompleted(this, new getNewEnergyVehicleInfoCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.mai.catarc.info/", ResponseNamespace="http://service.mai.catarc.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public qynameByYear[] getNerdsQyname([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password) {
            object[] results = this.Invoke("getNerdsQyname", new object[] {
                        username,
                        password});
            return ((qynameByYear[])(results[0]));
        }
        
        /// <remarks/>
        public void getNerdsQynameAsync(string username, string password) {
            this.getNerdsQynameAsync(username, password, null);
        }
        
        /// <remarks/>
        public void getNerdsQynameAsync(string username, string password, object userState) {
            if ((this.getNerdsQynameOperationCompleted == null)) {
                this.getNerdsQynameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNerdsQynameOperationCompleted);
            }
            this.InvokeAsync("getNerdsQyname", new object[] {
                        username,
                        password}, this.getNerdsQynameOperationCompleted, userState);
        }
        
        private void OngetNerdsQynameOperationCompleted(object arg) {
            if ((this.getNerdsQynameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNerdsQynameCompleted(this, new getNerdsQynameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.mai.catarc.info/", ResponseNamespace="http://service.mai.catarc.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public newEnergyVehicle[] getNewEnergyVehicleInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cpxh, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string year, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int pageSize, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int pageIndex) {
            object[] results = this.Invoke("getNewEnergyVehicleInfo", new object[] {
                        username,
                        password,
                        cpxh,
                        year,
                        pageSize,
                        pageIndex});
            return ((newEnergyVehicle[])(results[0]));
        }
        
        /// <remarks/>
        public void getNewEnergyVehicleInfoAsync(string username, string password, string cpxh, string year, int pageSize, int pageIndex) {
            this.getNewEnergyVehicleInfoAsync(username, password, cpxh, year, pageSize, pageIndex, null);
        }
        
        /// <remarks/>
        public void getNewEnergyVehicleInfoAsync(string username, string password, string cpxh, string year, int pageSize, int pageIndex, object userState) {
            if ((this.getNewEnergyVehicleInfoOperationCompleted == null)) {
                this.getNewEnergyVehicleInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewEnergyVehicleInfoOperationCompleted);
            }
            this.InvokeAsync("getNewEnergyVehicleInfo", new object[] {
                        username,
                        password,
                        cpxh,
                        year,
                        pageSize,
                        pageIndex}, this.getNewEnergyVehicleInfoOperationCompleted, userState);
        }
        
        private void OngetNewEnergyVehicleInfoOperationCompleted(object arg) {
            if ((this.getNewEnergyVehicleInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewEnergyVehicleInfoCompleted(this, new getNewEnergyVehicleInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.mai.catarc.info/", ResponseNamespace="http://service.mai.catarc.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string helloNewEnergyClearing([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username) {
            object[] results = this.Invoke("helloNewEnergyClearing", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void helloNewEnergyClearingAsync(string username) {
            this.helloNewEnergyClearingAsync(username, null);
        }
        
        /// <remarks/>
        public void helloNewEnergyClearingAsync(string username, object userState) {
            if ((this.helloNewEnergyClearingOperationCompleted == null)) {
                this.helloNewEnergyClearingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhelloNewEnergyClearingOperationCompleted);
            }
            this.InvokeAsync("helloNewEnergyClearing", new object[] {
                        username}, this.helloNewEnergyClearingOperationCompleted, userState);
        }
        
        private void OnhelloNewEnergyClearingOperationCompleted(object arg) {
            if ((this.helloNewEnergyClearingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.helloNewEnergyClearingCompleted(this, new helloNewEnergyClearingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.mai.catarc.info/")]
    public partial class qynameByYear {
        
        private string qymcField;
        
        private string yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qymc {
            get {
                return this.qymcField;
            }
            set {
                this.qymcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.mai.catarc.info/")]
    public partial class newEnergyVehicle {
        
        private string changField;
        
        private string cnzzscqyField;
        
        private string cpmcField;
        
        private string cpxhField;
        
        private string cxhcnzzxhField;
        
        private string ddqcqdcField;
        
        private string ddqcqdglField;
        
        private string ddqcqdxhField;
        
        private string ddqcxslcField;
        
        private string ddqcxslc_cunField;
        
        private string ddqcyblcField;
        
        private string ddqcyblc_cunField;
        
        private string dlxdccField;
        
        private string dlxdcxhField;
        
        private string dlxdczlField;
        
        private string ekgField;
        
        private string ggpcField;
        
        private string lbField;
        
        private string nerdspcField;
        
        private string noField;
        
        private string pz_idField;
        
        private string qymcField;
        
        private string rldcqpqyField;
        
        private string rldcqpxhField;
        
        private string rldcxtedglField;
        
        private string xnzzzdlField;
        
        private string yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string chang {
            get {
                return this.changField;
            }
            set {
                this.changField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cnzzscqy {
            get {
                return this.cnzzscqyField;
            }
            set {
                this.cnzzscqyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpmc {
            get {
                return this.cpmcField;
            }
            set {
                this.cpmcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpxh {
            get {
                return this.cpxhField;
            }
            set {
                this.cpxhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cxhcnzzxh {
            get {
                return this.cxhcnzzxhField;
            }
            set {
                this.cxhcnzzxhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ddqcqdc {
            get {
                return this.ddqcqdcField;
            }
            set {
                this.ddqcqdcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ddqcqdgl {
            get {
                return this.ddqcqdglField;
            }
            set {
                this.ddqcqdglField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ddqcqdxh {
            get {
                return this.ddqcqdxhField;
            }
            set {
                this.ddqcqdxhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ddqcxslc {
            get {
                return this.ddqcxslcField;
            }
            set {
                this.ddqcxslcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ddqcxslc_cun {
            get {
                return this.ddqcxslc_cunField;
            }
            set {
                this.ddqcxslc_cunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ddqcyblc {
            get {
                return this.ddqcyblcField;
            }
            set {
                this.ddqcyblcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ddqcyblc_cun {
            get {
                return this.ddqcyblc_cunField;
            }
            set {
                this.ddqcyblc_cunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dlxdcc {
            get {
                return this.dlxdccField;
            }
            set {
                this.dlxdccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dlxdcxh {
            get {
                return this.dlxdcxhField;
            }
            set {
                this.dlxdcxhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dlxdczl {
            get {
                return this.dlxdczlField;
            }
            set {
                this.dlxdczlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ekg {
            get {
                return this.ekgField;
            }
            set {
                this.ekgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ggpc {
            get {
                return this.ggpcField;
            }
            set {
                this.ggpcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lb {
            get {
                return this.lbField;
            }
            set {
                this.lbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nerdspc {
            get {
                return this.nerdspcField;
            }
            set {
                this.nerdspcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string no {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pz_id {
            get {
                return this.pz_idField;
            }
            set {
                this.pz_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qymc {
            get {
                return this.qymcField;
            }
            set {
                this.qymcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rldcqpqy {
            get {
                return this.rldcqpqyField;
            }
            set {
                this.rldcqpqyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rldcqpxh {
            get {
                return this.rldcqpxhField;
            }
            set {
                this.rldcqpxhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rldcxtedgl {
            get {
                return this.rldcxtedglField;
            }
            set {
                this.rldcxtedglField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xnzzzdl {
            get {
                return this.xnzzzdlField;
            }
            set {
                this.xnzzzdlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void checkEnterpriseCompletedEventHandler(object sender, checkEnterpriseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkEnterpriseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkEnterpriseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void getNewEnergyVehicleInfoCountCompletedEventHandler(object sender, getNewEnergyVehicleInfoCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewEnergyVehicleInfoCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewEnergyVehicleInfoCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void getNerdsQynameCompletedEventHandler(object sender, getNerdsQynameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNerdsQynameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNerdsQynameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public qynameByYear[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((qynameByYear[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void getNewEnergyVehicleInfoCompletedEventHandler(object sender, getNewEnergyVehicleInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewEnergyVehicleInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewEnergyVehicleInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public newEnergyVehicle[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((newEnergyVehicle[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void helloNewEnergyClearingCompletedEventHandler(object sender, helloNewEnergyClearingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class helloNewEnergyClearingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal helloNewEnergyClearingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591