//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelDataSysClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\\\\192.168.1.100\\lhhb\\data.mdb;Persis" +
            "t Security Info=True")]
        public string dataConnectionString {
            get {
                return ((string)(this["dataConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WsDXIP {
            get {
                return ((string)(this["WsDXIP"]));
            }
            set {
                this["WsDXIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProxy {
            get {
                return ((bool)(this["IsProxy"]));
            }
            set {
                this["IsProxy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyAddr {
            get {
                return ((string)(this["ProxyAddr"]));
            }
            set {
                this["ProxyAddr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyPort {
            get {
                return ((string)(this["ProxyPort"]));
            }
            set {
                this["ProxyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyUserId {
            get {
                return ((string)(this["ProxyUserId"]));
            }
            set {
                this["ProxyUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyPwd {
            get {
                return ((string)(this["ProxyPwd"]));
            }
            set {
                this["ProxyPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TimeConstrain {
            get {
                return ((int)(this["TimeConstrain"]));
            }
            set {
                this["TimeConstrain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate.xls")]
        public string ExcelHeaderTemplate {
            get {
                return ((string)(this["ExcelHeaderTemplate"]));
            }
            set {
                this["ExcelHeaderTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbPath {
            get {
                return ((string)(this["DbPath"]));
            }
            set {
                this["DbPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.catarc.info/CafcWebService.asmx")]
        public string FuelDataSysClient_CafcService_CafcWebService {
            get {
                return ((string)(this["FuelDataSysClient_CafcService_CafcWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.catarc.info/FuelDataOpen.asmx")]
        public string FuelDataSysClient_FuelDataOpen_FuelDataOpen {
            get {
                return ((string)(this["FuelDataSysClient_FuelDataOpen_FuelDataOpen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.catarc.info/Authority.asmx")]
        public string FuelDataSysClient_AuthorityManager_Authority {
            get {
                return ((string)(this["FuelDataSysClient_AuthorityManager_Authority"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\data\\data.mdb;Persis" +
            "t Security Info=True")]
        public string dataConnectionString1 {
            get {
                return ((string)(this["dataConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Qymc {
            get {
                return ((string)(this["Qymc"]));
            }
            set {
                this["Qymc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserId {
            get {
                return ((string)(this["UserId"]));
            }
            set {
                this["UserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPWD {
            get {
                return ((string)(this["UserPWD"]));
            }
            set {
                this["UserPWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CompareFlag {
            get {
                return ((bool)(this["CompareFlag"]));
            }
            set {
                this["CompareFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFuelTest {
            get {
                return ((bool)(this["IsFuelTest"]));
            }
            set {
                this["IsFuelTest"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tsoap.catarc.info/FuelDataSysWebService.asmx")]
        public string FuelDataSysClient_FuelDataService_FuelDataSysWebService {
            get {
                return ((string)(this["FuelDataSysClient_FuelDataService_FuelDataSysWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tsoap.catarc.info/FuelDataSysWebService.asmx")]
        public string FuelDataSysClient_FuelDataService_Service1 {
            get {
                return ((string)(this["FuelDataSysClient_FuelDataService_Service1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate_JBLH.xls")]
        public string ExcelHeaderTemplate_JBLH {
            get {
                return ((string)(this["ExcelHeaderTemplate_JBLH"]));
            }
            set {
                this["ExcelHeaderTemplate_JBLH"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\data\\data_JBLH.mdb;P" +
            "ersist Security Info=True")]
        public string data_JBLHConnectionString {
            get {
                return ((string)(this["data_JBLHConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate_BMW.xls")]
        public string ExcelHeaderTemplate_BMW {
            get {
                return ((string)(this["ExcelHeaderTemplate_BMW"]));
            }
            set {
                this["ExcelHeaderTemplate_BMW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate_Porsche.xls")]
        public string ExcelHeaderTemplate_Porsche {
            get {
                return ((string)(this["ExcelHeaderTemplate_Porsche"]));
            }
            set {
                this["ExcelHeaderTemplate_Porsche"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate_Mits.xls")]
        public string ExcelHeaderTemplate_Mits {
            get {
                return ((string)(this["ExcelHeaderTemplate_Mits"]));
            }
            set {
                this["ExcelHeaderTemplate_Mits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate_Toyota.xls")]
        public string ExcelHeaderTemplate_Toyota {
            get {
                return ((string)(this["ExcelHeaderTemplate_Toyota"]));
            }
            set {
                this["ExcelHeaderTemplate_Toyota"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate_ToyotaCompare.xls")]
        public string ExcelHeaderTemplate_ToyotaCompare {
            get {
                return ((string)(this["ExcelHeaderTemplate_ToyotaCompare"]));
            }
            set {
                this["ExcelHeaderTemplate_ToyotaCompare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate_Chrysler.xls")]
        public string ExcelHeaderTemplate_Chrysler {
            get {
                return ((string)(this["ExcelHeaderTemplate_Chrysler"]));
            }
            set {
                this["ExcelHeaderTemplate_Chrysler"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tsoap.catarc.info/FileUploadService.asmx")]
        public string FuelDataSysClient_FuelFileUpload_FileUploadService {
            get {
                return ((string)(this["FuelDataSysClient_FuelFileUpload_FileUploadService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\data\\data_Nissan.mdb" +
            ";Persist Security Info=True")]
        public string data_NissanConnectionString {
            get {
                return ((string)(this["data_NissanConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate_Nissan.xls")]
        public string ExcelHeaderTemplate_Nissan {
            get {
                return ((string)(this["ExcelHeaderTemplate_Nissan"]));
            }
            set {
                this["ExcelHeaderTemplate_Nissan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\ExcelHeaderTemplate_Volkswagen.xls")]
        public string ExcelHeaderTemplate_Volkswagen {
            get {
                return ((string)(this["ExcelHeaderTemplate_Volkswagen"]));
            }
            set {
                this["ExcelHeaderTemplate_Volkswagen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\ExcelHeaderTemplate\\menuData.XML")]
        public string MenuDataURL {
            get {
                return ((string)(this["MenuDataURL"]));
            }
            set {
                this["MenuDataURL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.catarc.info/CertificateComparison.asmx")]
        public string FuelDataSysClient_CertificateService_CertificateComparison {
            get {
                return ((string)(this["FuelDataSysClient_CertificateService_CertificateComparison"]));
            }
        }
    }
}
