//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.mai.catarc.info/", ConfigurationName="NewEnergyWeb.INewEnergyClearingService")]
    public interface INewEnergyClearingService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.checkEnterpriseResponse checkEnterprise(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.checkEnterprise request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoCountResponse getNewEnergyVehicleInfoCount(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoCount request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNerdsQynameResponse getNerdsQyname(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNerdsQyname request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoResponse getNewEnergyVehicleInfo(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfo request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.helloNewEnergyClearingResponse helloNewEnergyClearing(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.helloNewEnergyClearing request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkEnterprise", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class checkEnterprise {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qymc;
        
        public checkEnterprise() {
        }
        
        public checkEnterprise(string username, string password, string qymc) {
            this.username = username;
            this.password = password;
            this.qymc = qymc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkEnterpriseResponse", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class checkEnterpriseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public checkEnterpriseResponse() {
        }
        
        public checkEnterpriseResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewEnergyVehicleInfoCount", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class getNewEnergyVehicleInfoCount {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpxh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string year;
        
        public getNewEnergyVehicleInfoCount() {
        }
        
        public getNewEnergyVehicleInfoCount(string username, string password, string cpxh, string year) {
            this.username = username;
            this.password = password;
            this.cpxh = cpxh;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewEnergyVehicleInfoCountResponse", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class getNewEnergyVehicleInfoCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getNewEnergyVehicleInfoCountResponse() {
        }
        
        public getNewEnergyVehicleInfoCountResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNerdsQyname", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class getNerdsQyname {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string year;
        
        public getNerdsQyname() {
        }
        
        public getNerdsQyname(string username, string password, string year) {
            this.username = username;
            this.password = password;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNerdsQynameResponse", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class getNerdsQynameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getNerdsQynameResponse() {
        }
        
        public getNerdsQynameResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.mai.catarc.info/")]
    public partial class newEnergyVehicle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string changField;
        
        private string cnzzscqyField;
        
        private string cpmcField;
        
        private string cpxhField;
        
        private string cxhcnzzxhField;
        
        private string ddqcqdcField;
        
        private string ddqcqdglField;
        
        private string ddqcqdxhField;
        
        private string ddqcxslcField;
        
        private string ddqcxslc_cunField;
        
        private string ddqcyblcField;
        
        private string ddqcyblc_cunField;
        
        private string dlxdccField;
        
        private string dlxdcxhField;
        
        private string dlxdczlField;
        
        private string ekgField;
        
        private string ggpcField;
        
        private string lbField;
        
        private string nerdspcField;
        
        private string noField;
        
        private string pz_idField;
        
        private string qymcField;
        
        private string rldcqpqyField;
        
        private string rldcqpxhField;
        
        private string rldcxtedglField;
        
        private string xnzzzdlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chang {
            get {
                return this.changField;
            }
            set {
                this.changField = value;
                this.RaisePropertyChanged("chang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cnzzscqy {
            get {
                return this.cnzzscqyField;
            }
            set {
                this.cnzzscqyField = value;
                this.RaisePropertyChanged("cnzzscqy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cpmc {
            get {
                return this.cpmcField;
            }
            set {
                this.cpmcField = value;
                this.RaisePropertyChanged("cpmc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cpxh {
            get {
                return this.cpxhField;
            }
            set {
                this.cpxhField = value;
                this.RaisePropertyChanged("cpxh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cxhcnzzxh {
            get {
                return this.cxhcnzzxhField;
            }
            set {
                this.cxhcnzzxhField = value;
                this.RaisePropertyChanged("cxhcnzzxh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ddqcqdc {
            get {
                return this.ddqcqdcField;
            }
            set {
                this.ddqcqdcField = value;
                this.RaisePropertyChanged("ddqcqdc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ddqcqdgl {
            get {
                return this.ddqcqdglField;
            }
            set {
                this.ddqcqdglField = value;
                this.RaisePropertyChanged("ddqcqdgl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ddqcqdxh {
            get {
                return this.ddqcqdxhField;
            }
            set {
                this.ddqcqdxhField = value;
                this.RaisePropertyChanged("ddqcqdxh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ddqcxslc {
            get {
                return this.ddqcxslcField;
            }
            set {
                this.ddqcxslcField = value;
                this.RaisePropertyChanged("ddqcxslc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ddqcxslc_cun {
            get {
                return this.ddqcxslc_cunField;
            }
            set {
                this.ddqcxslc_cunField = value;
                this.RaisePropertyChanged("ddqcxslc_cun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ddqcyblc {
            get {
                return this.ddqcyblcField;
            }
            set {
                this.ddqcyblcField = value;
                this.RaisePropertyChanged("ddqcyblc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ddqcyblc_cun {
            get {
                return this.ddqcyblc_cunField;
            }
            set {
                this.ddqcyblc_cunField = value;
                this.RaisePropertyChanged("ddqcyblc_cun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string dlxdcc {
            get {
                return this.dlxdccField;
            }
            set {
                this.dlxdccField = value;
                this.RaisePropertyChanged("dlxdcc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string dlxdcxh {
            get {
                return this.dlxdcxhField;
            }
            set {
                this.dlxdcxhField = value;
                this.RaisePropertyChanged("dlxdcxh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string dlxdczl {
            get {
                return this.dlxdczlField;
            }
            set {
                this.dlxdczlField = value;
                this.RaisePropertyChanged("dlxdczl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ekg {
            get {
                return this.ekgField;
            }
            set {
                this.ekgField = value;
                this.RaisePropertyChanged("ekg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ggpc {
            get {
                return this.ggpcField;
            }
            set {
                this.ggpcField = value;
                this.RaisePropertyChanged("ggpc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string lb {
            get {
                return this.lbField;
            }
            set {
                this.lbField = value;
                this.RaisePropertyChanged("lb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string nerdspc {
            get {
                return this.nerdspcField;
            }
            set {
                this.nerdspcField = value;
                this.RaisePropertyChanged("nerdspc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string no {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string pz_id {
            get {
                return this.pz_idField;
            }
            set {
                this.pz_idField = value;
                this.RaisePropertyChanged("pz_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string qymc {
            get {
                return this.qymcField;
            }
            set {
                this.qymcField = value;
                this.RaisePropertyChanged("qymc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string rldcqpqy {
            get {
                return this.rldcqpqyField;
            }
            set {
                this.rldcqpqyField = value;
                this.RaisePropertyChanged("rldcqpqy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string rldcqpxh {
            get {
                return this.rldcqpxhField;
            }
            set {
                this.rldcqpxhField = value;
                this.RaisePropertyChanged("rldcqpxh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string rldcxtedgl {
            get {
                return this.rldcxtedglField;
            }
            set {
                this.rldcxtedglField = value;
                this.RaisePropertyChanged("rldcxtedgl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string xnzzzdl {
            get {
                return this.xnzzzdlField;
            }
            set {
                this.xnzzzdlField = value;
                this.RaisePropertyChanged("xnzzzdl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewEnergyVehicleInfo", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class getNewEnergyVehicleInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpxh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageIndex;
        
        public getNewEnergyVehicleInfo() {
        }
        
        public getNewEnergyVehicleInfo(string username, string password, string cpxh, string year, int pageSize, int pageIndex) {
            this.username = username;
            this.password = password;
            this.cpxh = cpxh;
            this.year = year;
            this.pageSize = pageSize;
            this.pageIndex = pageIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewEnergyVehicleInfoResponse", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class getNewEnergyVehicleInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.newEnergyVehicle[] @return;
        
        public getNewEnergyVehicleInfoResponse() {
        }
        
        public getNewEnergyVehicleInfoResponse(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.newEnergyVehicle[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloNewEnergyClearing", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class helloNewEnergyClearing {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public helloNewEnergyClearing() {
        }
        
        public helloNewEnergyClearing(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloNewEnergyClearingResponse", WrapperNamespace="http://service.mai.catarc.info/", IsWrapped=true)]
    public partial class helloNewEnergyClearingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mai.catarc.info/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloNewEnergyClearingResponse() {
        }
        
        public helloNewEnergyClearingResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewEnergyClearingServiceChannel : Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewEnergyClearingServiceClient : System.ServiceModel.ClientBase<Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService>, Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService {
        
        public NewEnergyClearingServiceClient() {
        }
        
        public NewEnergyClearingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewEnergyClearingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewEnergyClearingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewEnergyClearingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.checkEnterpriseResponse Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService.checkEnterprise(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.checkEnterprise request) {
            return base.Channel.checkEnterprise(request);
        }
        
        public string checkEnterprise(string username, string password, string qymc) {
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.checkEnterprise inValue = new Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.checkEnterprise();
            inValue.username = username;
            inValue.password = password;
            inValue.qymc = qymc;
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.checkEnterpriseResponse retVal = ((Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService)(this)).checkEnterprise(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoCountResponse Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService.getNewEnergyVehicleInfoCount(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoCount request) {
            return base.Channel.getNewEnergyVehicleInfoCount(request);
        }
        
        public int getNewEnergyVehicleInfoCount(string username, string password, string cpxh, string year) {
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoCount inValue = new Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoCount();
            inValue.username = username;
            inValue.password = password;
            inValue.cpxh = cpxh;
            inValue.year = year;
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoCountResponse retVal = ((Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService)(this)).getNewEnergyVehicleInfoCount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNerdsQynameResponse Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService.getNerdsQyname(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNerdsQyname request) {
            return base.Channel.getNerdsQyname(request);
        }
        
        public string[] getNerdsQyname(string username, string password, string year) {
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNerdsQyname inValue = new Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNerdsQyname();
            inValue.username = username;
            inValue.password = password;
            inValue.year = year;
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNerdsQynameResponse retVal = ((Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService)(this)).getNerdsQyname(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoResponse Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService.getNewEnergyVehicleInfo(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfo request) {
            return base.Channel.getNewEnergyVehicleInfo(request);
        }
        
        public Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.newEnergyVehicle[] getNewEnergyVehicleInfo(string username, string password, string cpxh, string year, int pageSize, int pageIndex) {
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfo inValue = new Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfo();
            inValue.username = username;
            inValue.password = password;
            inValue.cpxh = cpxh;
            inValue.year = year;
            inValue.pageSize = pageSize;
            inValue.pageIndex = pageIndex;
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.getNewEnergyVehicleInfoResponse retVal = ((Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService)(this)).getNewEnergyVehicleInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.helloNewEnergyClearingResponse Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService.helloNewEnergyClearing(Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.helloNewEnergyClearing request) {
            return base.Channel.helloNewEnergyClearing(request);
        }
        
        public string helloNewEnergyClearing(string username) {
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.helloNewEnergyClearing inValue = new Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.helloNewEnergyClearing();
            inValue.username = username;
            Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.helloNewEnergyClearingResponse retVal = ((Catarc.Adc.NewEnergyAccountSys.NewEnergyWeb.INewEnergyClearingService)(this)).helloNewEnergyClearing(inValue);
            return retVal.@return;
        }
    }
}
