//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 网络中断，升级失败，请稍后再试！ 的本地化字符串。
        /// </summary>
        internal static string ConnectionInterrupted {
            get {
                return ResourceManager.GetString("ConnectionInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在分析升级信息...... 的本地化字符串。
        /// </summary>
        internal static string InitialInformation {
            get {
                return ResourceManager.GetString("InitialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录不成功！ 的本地化字符串。
        /// </summary>
        internal static string LogonFailed {
            get {
                return ResourceManager.GetString("LogonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共需更新 的本地化字符串。
        /// </summary>
        internal static string NeedUpdate_string1 {
            get {
                return ResourceManager.GetString("NeedUpdate_string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个文件，正在分析中...... 的本地化字符串。
        /// </summary>
        internal static string NeedUpdate_string2 {
            get {
                return ResourceManager.GetString("NeedUpdate_string2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有文件需要更新 的本地化字符串。
        /// </summary>
        internal static string NoFileNeedUpdate {
            get {
                return ResourceManager.GetString("NoFileNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标程序正在运行中，请先退出程序，再执行升级！ 的本地化字符串。
        /// </summary>
        internal static string TargetIsRunning {
            get {
                return ResourceManager.GetString("TargetIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败！ 的本地化字符串。
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共需更新 的本地化字符串。
        /// </summary>
        internal static string Updateing_string1 {
            get {
                return ResourceManager.GetString("Updateing_string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个文件，正在更新第 的本地化字符串。
        /// </summary>
        internal static string Updateing_string2 {
            get {
                return ResourceManager.GetString("Updateing_string2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个文件...... 的本地化字符串。
        /// </summary>
        internal static string Updateing_string3 {
            get {
                return ResourceManager.GetString("Updateing_string3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功！ 的本地化字符串。
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
